"""Unified location for capturing measurements related to the robot."""

# Locations (in meters)
SWERVE_FRONT_LEFT_LOCATION_X = 0.342
SWERVE_FRONT_LEFT_LOCATION_Y = 0.381
SWERVE_FRONT_RIGHT_LOCATION_X = 0.342
SWERVE_FRONT_RIGHT_LOCATION_Y = -0.381

SWERVE_REAR_LEFT_LOCATION_X = -0.273
SWERVE_REAR_LEFT_LOCATION_Y = 0.381
SWERVE_REAR_RIGHT_LOCATION_X = -0.273
SWERVE_REAR_RIGHT_LOCATION_Y = -0.381

SHOOTER_OFFSET_Z = 0.421
SHOOTER_MAX_ANGLE_DEGREES = 34
